### PR TITLE
Changed that the "now"-line was barely visible in darkmode

### PR DESCRIPTION
**Pull request by Tagirijus**
To me the "now line" was to dark in the darkmode, yet in the lightmode it is quite visible. So I changed the color a tiny bit to the text color. Maybe you find this tweak useful. (=

### CODE REVIEW

**Comment by almarklein** [comment]
Thanks! Looks good, but CI is broken due to upstream changes. Will look into that when I'm back at the office.

**Comment by almarklein** [comment]
If you merge with the latest `main`, the errors should be gone.

**Comment by almarklein** [comment]
Oh wait, this is literally one line. Merging! 

Thanks!

**Comment by Tagirijus** [comment]
Cool, thank your for the reply and for the merge! I am glad that so far my PRs were helpful (hopefully, hehe). (=

**Pull request merged**
